name: Step 3

on:
  issue_comment:
    types:
      - edited

concurrency: step-3

permissions:
  contents: write
  actions: write
  issues: write

env:
  STEP_4_FILE: ".github/steps/4-step.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.2

  check_step:
    name: Check step
    runs-on: ubuntu-latest

    outputs:
      is-step-complete: ${{ steps.is-step-complete.outputs.is-step-complete }}

    steps:
      - name: Verify comment body includes step number and a checked box
        uses: actions/github-script@v6
        id: is-step-complete
        with:
          script: |
            // Get comment body
            const commentBody = process.env.COMMENT_BODY || '';

            // Check for Step number and checked box
            const stepNumberFound = commentBody.includes(process.env.STEP_MARKER);
            const checkboxCheckFound = commentBody.includes('- [x]');

            // Save result as output
            const isStepComplete = stepNumberFound && checkboxCheckFound;
            core.setOutput('is-step-complete', isStepComplete);
        env:
          STEP_MARKER: "Step 3"
          COMMENT_BODY: ${{ github.event.comment.body }}

  post_next_step_content:
    name: Post next step content
    needs: [find_exercise, check_step]
    runs-on: ubuntu-latest
    if: ${{ needs.check_step.outputs.is-step-complete == 'true' }}

    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Get response templates
      #   uses: actions/checkout@v4
      #   with:
      #     repository: skills/exercise-toolkit
      #     path: exercise-toolkit
      #     ref: v0.7.2

      # - name: Create comment - step finished
      #   uses: GrantBirki/comment@v2.1.1
      #   with:
      #     repository: ${{ env.ISSUE_REPOSITORY }}
      #     issue-number: ${{ env.ISSUE_NUMBER }}
      #     file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
      #     vars: |
      #       next_step_number: 4

      - name: Create comment - add step content
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_4_FILE }}

      # - name: Create comment - watching for progress
      #   uses: GrantBirki/comment@v2.1.1
      #   with:
      #     repository: ${{ env.ISSUE_REPOSITORY }}
      #     issue-number: ${{ env.ISSUE_NUMBER }}
      #     file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md

      - name: Disable current workflow and enable next one
        run: |
          gh workflow disable "${{github.workflow}}"
          gh workflow enable "Step 4"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
