name: Step 5

on:
  issue_comment:
    types:
      - edited

concurrency: step-5

permissions:
  contents: write
  actions: write
  issues: write

env:
  REVIEW_FILE: ".github/steps/x-review.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.2

  check_step:
    name: Check step
    runs-on: ubuntu-latest

    outputs:
      is-step-complete: ${{ steps.is-step-complete.outputs.is-step-complete }}

    steps:
      - name: Verify comment body includes step number and a checked box
        uses: actions/github-script@v6
        id: is-step-complete
        with:
          script: |
            // Get comment body
            const commentBody = process.env.COMMENT_BODY || '';

            // Check for Step number and checked box
            const stepNumberFound = commentBody.includes(process.env.STEP_MARKER);
            const checkboxCheckFound = commentBody.includes('- [x]');

            // Save result as output
            const isStepComplete = stepNumberFound && checkboxCheckFound;
            core.setOutput('is-step-complete', isStepComplete);
        env:
          STEP_MARKER: "Step 5"
          COMMENT_BODY: ${{ github.event.comment.body }}

  post_review_content:
    name: Post review content
    needs: [find_exercise, check_step]
    runs-on: ubuntu-latest
    if: ${{ needs.check_step.outputs.is-step-complete == 'true' }}

    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Get response templates
      #   uses: actions/checkout@v4
      #   with:
      #     repository: skills/exercise-toolkit
      #     path: exercise-toolkit
      #     ref: v0.7.2

      # - name: Create comment - step finished - final review next
      #   uses: GrantBirki/comment@v2.1.1
      #   with:
      #     repository: ${{ env.ISSUE_REPOSITORY }}
      #     issue-number: ${{ env.ISSUE_NUMBER }}
      #     file: exercise-toolkit/markdown-templates/step-feedback/lesson-review.md

      - name: Create comment - add review content
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.REVIEW_FILE }}

      - name: Disable current workflow
        run: gh workflow disable "${{github.workflow}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish_exercise:
    name: Finish Exercise
    needs: [find_exercise, post_review_content]
    uses: skills/exercise-toolkit/.github/workflows/finish-exercise.yml@v0.7.2
    with:
      issue-url: ${{ needs.find_exercise.outputs.issue-url }}
      exercise-title: "Idea to App with GitHub Spark"
